### ISSUE TITLE
Integrating in rails 3 app

### ISSUE THREAD

**Issue by miclovich** [andrewhavens/mad_chatter#19]
Hey Andrew, how can mad_chatter be integrated in an rails 3 app?

Is it just by placing a gem reference in the Gemfile or the app or is it something more complex?

**Comment by andrewhavens** [comment]
Hi, thanks for the question. As it exists right now, Mad Chatter is more of a standalone application, rather than a gem you add to a Rails Gemfile. Once you install Mad Chatter, you can use its generator and server commands to run it. However, the client side HTML is available to customize, so if you already have a Rails 3 app and you want to provide a link to the chat application, or customize it to match the look an feel of your app you can do that (but it is more of a manual process). I would recommend installing it (gem install mad_chatter), generating a new app (mad_chatter new myapp) and running it (cd myapp; mad_chatter preview) in order to get a feel for how it works.

I hope that helps. Let me know how you plan on using it. I'd be curious to know how I can improve it to fit your scenario.

--Andrew

**Comment by andrewhavens** [comment]
@miclovich you sparked an idea for me by asking this question. I am embarking on a major refactoring of Mad Chatter to make it easier to add Mad Chatter to an existing Rails application. When I'm done, it will be as easy as adding it to your Gemfile. Thanks again for submitting an issue and taking an interest in my project. I'll let you know when I am finished.

**Comment by miclovich** [comment]
that's awesome... :)

**Comment by ixevix** [comment]
Hey, I was looking into MadChatter as an option for implementing debrief chat for our game service. I see it has been three weeks since the last comment. Has there been any progress for integrating this into an existing rails project? This piece of software could be very useful for our purpose with some modifications.

**Comment by miclovich** [comment]
Yes.. its been a while. I think I'll have to look at the code myself and chat about how well we can integrate this to Madchatter. But Andrew pointed it out; it will be a major refactor for MadChatter to become a standalone gem.

**Comment by andrewhavens** [comment]
Sorry, I've been MIA lately. I'm the father of an 8 week old now, so that's been occupying my free time. I have some pretty major changes planned for Mad Chatter. Let me know what you think of this plan:
- Turn Mad Chatter into a standard Rack mountable application to make it easy and intuitive to deploy.
- Create a Rails engine that wraps this new Rack application to make it easy to integrate into an existing Rails application.
- Switch from using em-websocket to using Faye to provide long-polling support (which will make it so you can host it on Heroku). This change will require Redis as a dependency, but I think it will be worth it in the end.
- When you generate a standalone version of Mad Chatter, you will get a directory structure that will contain a Gemfile, a standard config.ru, and a way to override specific views, rather than providing all of the views for you to have to maintain (much like how Refinery CMS or a standard Rails engine works).

I think that covers the bulk of the changes I had planned. This will be a relatively major change and may take some time to finish and get right.

Also, I will eventually move this project to its own GitHub organization so I can group all of the Mad Chatter related projects in one place, but I will let everyone know when that happens.

Sound good?

**Comment by ixevix** [comment]
Sounds great. Congratulations on the addition to the family!

**Comment by andrewhavens** [comment]
Thanks! The other thing I forgot to mention (and this is more of a feature add than a change) is that I am going to add user authentication. Mad Chatter needs this so users can save messages, rooms, friends lists, etc. and provide the ability to keep out non-authenticated users. I plan on implementing this in a way that allows you to reuse an existing devise, auth logic, omniauth, install.

**Comment by miclovich** [comment]
sounds great @andrewhavens and congrats on the new addition to the family.

**Comment by soorajb** [comment]
Great! @andrewhavens and congrats!

**Comment by shideneyu** [comment]
Hello @andrewhavens, congratulation for your family.

I just discovered mad_chatter, and I'm pleased to see that you are planning to implement your project into an existing rails app as a gem.
However, you are planning to use "Faye", and it will require to use a different server than the one that people are using on normal times; I was looking for an alternative to Faye (or even private_pub), but both are using their own servers...
I'm new to rails and I would like to build a chat application using rails an ajax, however, keeping the connection open seems to be impossible by normal means.

Thanks you anyways for having the time in developping this great project which will help a lot of users here :)

**Comment by kirantpatil** [comment]
+1. Very nice feature. Thanks a ton to @andrewhavens

**Comment by kirantpatil** [comment]
@andrewhavens congratulations for becoming a father. 

Could you please share/upload your development repository which is getting developed offline on your laptop, so that others can work on it and make the development fast.

**Comment by nekapoor** [comment]
any updates on changing mad chatter into a gem that can be integrated into a rails 3 application?

THANKS!

**Comment by andrewhavens** [comment]
@nekapoor Yes! Mad Chatter was not dead, just hibernating. To be honest, I have been working on a few really cool projects that have put Mad Chatter on the back burner for far too long. I've also rewritten Mad Chatter 3 or 4 times now, each taking a different direction. I have settled on the path of least resistance by creating a gem that is only available as a Rails Engine since that seems to be the most requested feature. I also think this will make it easier for people to use and contribute to.

Mad Chatter now has a new home: https://github.com/madchatter/mad_chatter

It's a complete rewrite so it's still pretty rough, but I have implemented some basic functionality. I decided to publish what I have so far to the repository so that my current status is public and everyone can see when I make updates (and can help out if they want).

Sorry for the lack of communication, but thanks everyone for all your support!

CC: @miclovich @ixevix @soorajb @shideneyu
